/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.MainClass;

/**
 *
 * @author SANTIAGO
 */
public class Animals_Control extends javax.swing.JFrame {
    
    MainClass mainClass;
    /**
     * Creates new form Animals_Control
     */
    public Animals_Control(MainClass mainClass) {
        initComponents();
        this.mainClass =  mainClass;
        setLocationRelativeTo(this);
        
    }

    Animals_Control() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonEditAnimals = new javax.swing.JButton();
        buttonEditDomestic = new javax.swing.JButton();
        buttonEditMinors = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        buttonEditSavages = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("CONTROL DE ANIMALES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 259, 55));

        buttonEditAnimals.setBackground(new java.awt.Color(0, 0, 102));
        buttonEditAnimals.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        buttonEditAnimals.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditAnimals.setText("Ver Animales");
        buttonEditAnimals.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonEditAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditAnimalsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditAnimals, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 322, 45));

        buttonEditDomestic.setBackground(new java.awt.Color(0, 0, 102));
        buttonEditDomestic.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        buttonEditDomestic.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditDomestic.setText("Editar Domesticos");
        buttonEditDomestic.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonEditDomestic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditDomesticActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditDomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 322, 45));

        buttonEditMinors.setBackground(new java.awt.Color(0, 0, 102));
        buttonEditMinors.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        buttonEditMinors.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditMinors.setText("Editar Menores");
        buttonEditMinors.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonEditMinors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditMinorsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditMinors, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 320, 50));

        buttonBack.setBackground(new java.awt.Color(0, 0, 102));
        buttonBack.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        buttonBack.setForeground(new java.awt.Color(255, 255, 255));
        buttonBack.setText("Regresar");
        buttonBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 320, 50));

        buttonEditSavages.setBackground(new java.awt.Color(0, 0, 102));
        buttonEditSavages.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        buttonEditSavages.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditSavages.setText("Editar Salvajes");
        buttonEditSavages.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonEditSavages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditSavagesActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditSavages, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 320, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditAnimalsActionPerformed
        // TODO add your handling code here:
       View_Animals view_Animals =  new View_Animals(mainClass);
       view_Animals.setVisible(true);
       dispose();
    }//GEN-LAST:event_buttonEditAnimalsActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        Main_Menu main_Menu =  new Main_Menu(mainClass);
        main_Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonEditDomesticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditDomesticActionPerformed
        // TODO add your handling code here:
        Edit_DomesticAnimals edit_DomesticAnimals =  new Edit_DomesticAnimals(mainClass);
        edit_DomesticAnimals.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEditDomesticActionPerformed

    private void buttonEditSavagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditSavagesActionPerformed
        // TODO add your handling code here:
        Edit_SavageAnimals edit_SavageAnimals = new Edit_SavageAnimals(mainClass);
        edit_SavageAnimals.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEditSavagesActionPerformed

    private void buttonEditMinorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditMinorsActionPerformed
        // TODO add your handling code here:
        Edit_MinorAnimals edit_MinorAnimals = new Edit_MinorAnimals(mainClass);
        edit_MinorAnimals.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEditMinorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animals_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animals_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animals_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animals_Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animals_Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonEditAnimals;
    private javax.swing.JButton buttonEditDomestic;
    private javax.swing.JButton buttonEditMinors;
    private javax.swing.JButton buttonEditSavages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
