/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DptLogistic;
import control.DptSales;
import control.MainClass;

/**
 *
 * @author SANTIAGO
 */
public class Main_Menu extends javax.swing.JFrame {
    //DptLogistic dptLogistic;
    //DptSales dptSales;
    MainClass mainClass;
    /**
     * Creates new form Main_Menu
     */
    public Main_Menu(MainClass mainClass) {
        initComponents();
        this.mainClass = mainClass;
        setLocationRelativeTo(this);
    }

    Main_Menu() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonAnimalControl = new javax.swing.JButton();
        buttonTicketsControl = new javax.swing.JButton();
        buttonPassesContro = new javax.swing.JButton();
        buttonPlansControl = new javax.swing.JButton();
        buttonSouvenirControl = new javax.swing.JButton();
        buttonAccountingControl = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(500, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("MENÚ PRINCIPAL");

        buttonAnimalControl.setBackground(new java.awt.Color(0, 0, 102));
        buttonAnimalControl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonAnimalControl.setForeground(new java.awt.Color(255, 255, 255));
        buttonAnimalControl.setText("Gestionar Animales");
        buttonAnimalControl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonAnimalControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnimalControlActionPerformed(evt);
            }
        });

        buttonTicketsControl.setBackground(new java.awt.Color(0, 0, 102));
        buttonTicketsControl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonTicketsControl.setForeground(new java.awt.Color(255, 255, 255));
        buttonTicketsControl.setText("Gestionar boletas");
        buttonTicketsControl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonTicketsControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTicketsControlActionPerformed(evt);
            }
        });

        buttonPassesContro.setBackground(new java.awt.Color(0, 0, 102));
        buttonPassesContro.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonPassesContro.setForeground(new java.awt.Color(255, 255, 255));
        buttonPassesContro.setText("Gestionar Abonos");
        buttonPassesContro.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonPassesContro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPassesControActionPerformed(evt);
            }
        });

        buttonPlansControl.setBackground(new java.awt.Color(0, 0, 102));
        buttonPlansControl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonPlansControl.setForeground(new java.awt.Color(255, 255, 255));
        buttonPlansControl.setText("Gestionar Planes");
        buttonPlansControl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonPlansControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlansControlActionPerformed(evt);
            }
        });

        buttonSouvenirControl.setBackground(new java.awt.Color(0, 0, 102));
        buttonSouvenirControl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonSouvenirControl.setForeground(new java.awt.Color(255, 255, 255));
        buttonSouvenirControl.setText("Gestionar Souvenirs");
        buttonSouvenirControl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonSouvenirControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSouvenirControlActionPerformed(evt);
            }
        });

        buttonAccountingControl.setBackground(new java.awt.Color(0, 0, 102));
        buttonAccountingControl.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonAccountingControl.setForeground(new java.awt.Color(255, 255, 255));
        buttonAccountingControl.setText("Gestionar Contabilidad");
        buttonAccountingControl.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonAccountingControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccountingControlActionPerformed(evt);
            }
        });

        buttonClose.setBackground(new java.awt.Color(0, 0, 102));
        buttonClose.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        buttonClose.setForeground(new java.awt.Color(255, 255, 255));
        buttonClose.setText("Salir");
        buttonClose.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPlansControl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAnimalControl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTicketsControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSouvenirControl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPassesContro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAccountingControl, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAnimalControl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTicketsControl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPassesContro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPlansControl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSouvenirControl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAccountingControl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTicketsControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTicketsControlActionPerformed
        // TODO add your handling code here:
        Tickest_Control tickest_Control = new Tickest_Control(mainClass);
        tickest_Control.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonTicketsControlActionPerformed

    private void buttonAnimalControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnimalControlActionPerformed
        // TODO add your handling code here:
        Animals_Control animals_Control = new Animals_Control(mainClass);
        animals_Control.setVisible(true);
        dispose();
   
    }//GEN-LAST:event_buttonAnimalControlActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonPlansControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlansControlActionPerformed
        // TODO add your handling code here:
        Plans_Control plans_Control = new Plans_Control(mainClass);
        plans_Control.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPlansControlActionPerformed

    private void buttonSouvenirControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSouvenirControlActionPerformed
        // TODO add your handling code here:
        Souvenir_Control souvenir_Control = new Souvenir_Control(mainClass);
        souvenir_Control.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonSouvenirControlActionPerformed

    private void buttonPassesControActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPassesControActionPerformed
        // TODO add your handling code here:
        Passes_Control passes_Control = new Passes_Control(mainClass);
        passes_Control.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPassesControActionPerformed

    private void buttonAccountingControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccountingControlActionPerformed
        // TODO add your handling code here:
        Accounting_Control accounting_Control = new Accounting_Control(mainClass);
        accounting_Control.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonAccountingControlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAccountingControl;
    private javax.swing.JButton buttonAnimalControl;
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonPassesContro;
    private javax.swing.JButton buttonPlansControl;
    private javax.swing.JButton buttonSouvenirControl;
    private javax.swing.JButton buttonTicketsControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
