
package view;
//import control.DptLogistic;
//import control.DptSales;
import utility.MinorAnimal;
import utility.DomesticAnimal;
import utility.SavageAnimal;
import utility.Ticket;
import control.MainClass;
import utility.Souvenir;
import utility.Pass;
import utility.Plan;

/**
 *
 * @author SANTIAGO
 */
public class Start_Page extends javax.swing.JFrame {
            
    //DptLogistic dptLogistic;
    //DptSales dptSales;
    MainClass mainClass;
    
    
    public Start_Page() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonStart.setBackground(new java.awt.Color(0, 0, 102));
        buttonStart.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        buttonStart.setForeground(new java.awt.Color(255, 255, 255));
        buttonStart.setText("Iniciar");
        buttonStart.setAlignmentY(0.0F);
        buttonStart.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonStart.setFocusPainted(false);
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });
        jPanel1.add(buttonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 128, 51));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO AL ZOOLÓGICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 320, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel3.setText("XXXXXX");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
            // TODO add your handling code here:
            //definimos todos los valores por defecto que vamos a usar
            MainClass mainClass = new MainClass();
            DomesticAnimal domesticAnimal = new DomesticAnimal("canino", "alto", "001", "firulais", "20 kg", "domestico");
            SavageAnimal savageAnimal = new SavageAnimal("medio", "nevados", "pinguino", "002", "pingui", "18 kg", "salvaje");
            MinorAnimal minorAnimal = new MinorAnimal("lemur", "bosques", "ni idea", "003", "rey julien", "15kg", "menor");
            Ticket ticket_kids = new Ticket(6000, "001", 12);
            Ticket ticket_adults = new Ticket(10000, "002", 999);
            Souvenir souvenir1 = new Souvenir("001", "oso de peluche de leon", 35000);
            Souvenir souvenir2 = new Souvenir("002", "oso de peluche de tigre", 35000);
            Pass pass1 = new Pass(100000, "001", 13);
            Pass pass2 = new Pass(80000, "002", 10);
            Plan plan1 = new Plan("001", "extremo", 200000, "4 horas", "alimentar a los animales salvajes del zoo", "lunes", "de 8am a 12pm", 20, 150000, true, 0, 0, 0);
            Plan plan2 = new Plan("002", "calmado", 100000, "4 horas", "alimentar a los animales salvajes del zoo", "viernes", "de 8am a 12pm", 80, 70000, false, 0, 0, 0);
            Plan plan3 = new Plan("003", "normal", 170000, "4 horas", "alimentar a los animales salvajes del zoo", "miercoles", "de 8am a 12pm", 8, 140000, false, 0, 0, 0);
            mainClass.getDptLogistic().addDomesticAnimals(domesticAnimal);
            mainClass.getDptLogistic().addSavageAnimals(savageAnimal);
            mainClass.getDptLogistic().addMinorAnimals(minorAnimal);
            mainClass.getDptSales().newTicket(ticket_kids);
            mainClass.getDptSales().newTicket(ticket_adults);
            mainClass.getDptSales().newSouvenir(souvenir1);
            mainClass.getDptSales().newSouvenir(souvenir2);
            mainClass.getDptSales().newPass(pass1);
            mainClass.getDptSales().newPass(pass2);
            mainClass.getDptSales().newPlan(plan1);
            mainClass.getDptSales().newPlan(plan2);
            mainClass.getDptSales().newPlan(plan3);
            Main_Menu main_Menu = new Main_Menu(mainClass);
            main_Menu.setVisible(true);
            dispose();
    }//GEN-LAST:event_buttonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
